### PR TITLE
Fix forced sign-out

### LINKED ISSUE #1282: Logging out remote users doesn't log them out from the UI
They're only logged out if they refresh the page:

Peek 2024-07-02 16-52

### PR DESCRIPTION
**Pull request by axelboc**
Fix #1282

Easy fix! :tada: 

... too easy? :joy_cat:

### CODE REVIEW

File: ui/src/serverIO.js [hunk 1]
```diff
@@ -413,8 +413,7 @@ class ServerIO {
     });
 
     this.hwrSocket.on('forceSignout', () => {
-      this.dispatch(forcedSignout());
-      serverIO.disconnect();
```
Comment (axelboc) [inline ui/src/serverIO.js:419]: Don't think we want to disconnect the WS connection, since we connect _before_ logging in, in `App`.

**Comment by marcus-oscarsson** [comment]
:+1:
